#!/bin/bash
set -euxo pipefail

python3 -m venv .venv

.venv/bin/python -m pip install --upgrade pip
.venv/bin/python -m pip install "ga4gh.gkm[notebooks]" --pre

.venv/bin/python -m ipykernel install \
    --prefix="${CONDA_PREFIX}" \
    --name="gkm_toolkit" \
    --display-name="GKM Toolkit Kernel"
